Repository skrub-data/skrub, pull requests merged in 2022-09, with the labels that each got.

#298 Clean GapEncoder test
  dirty_cat/test/test_gap_encoder.py
Labels: CI / Build

#327 Update contribution guidelines
  CONTRIBUTING.md
Labels: Documentation

#300 Binary encoding for features with cardinality <= 2
  CHANGES.rst
  README.rst
  dirty_cat/gap_encoder.py
  dirty_cat/super_vectorizer.py
  dirty_cat/test/test_super_vectorizer.py
  dirty_cat/utils.py
  requirements-min.txt
  setup.py
Labels: enhancement

#301 Implement CodeQL
  .github/workflows/codeql-analysis.yml
Labels: CI / Build

#350 DOC Add contrib docs to webpage
  .gitignore
  CHANGES.rst
  RELEASE_PROCESS.md
  RELEASE_PROCESS.rst
  doc/CHANGES.rst
  doc/_static/custom.css
  doc/conf.py
  doc/development.rst
  doc/index.rst
Labels: Documentation

#348 Update release process
  RELEASE_PROCESS.rst
Labels: Documentation

#364 Restore test_docstrings.py
  dirty_cat/tests/test_docstrings.py
Labels: bug

#366 Fix `test_docstrings.py`
  dirty_cat/tests/test_docstrings.py
  requirements-min.txt
  requirements.txt
Labels: bug, CI / Build

#367 DOC Ensures that DatetimeEncoder.fit passes numpydoc validation
  dirty_cat/_datetime_encoder.py
  dirty_cat/tests/test_docstrings.py
Labels: Documentation
