Repository skrub-data/skrub, pull requests merged in 2022-11, with the labels that each got.

#399 DOC Ensures that `SuperVectorizer` passes numpydoc validation
  dirty_cat/_super_vectorizer.py
  dirty_cat/tests/test_docstrings.py
Labels: Documentation

#329 New README proposal
  README.rst
  doc/index.rst
Labels: Documentation

#412 Set random state parameter in test data generation function
  dirty_cat/tests/test_gap_encoder.py
  dirty_cat/tests/utils.py
Labels: bug, CI / Build

#415 DOC Replace get_feature_names by get_feature_names_out
  dirty_cat/_similarity_encoder.py
Labels: Documentation

#414 DOC Fix readme
  README.rst
Labels: Documentation

#410 Use `sklearn.utils.parse_version` instead of `Version`
  dirty_cat/_datetime_encoder.py
  dirty_cat/_gap_encoder.py
  dirty_cat/_similarity_encoder.py
  dirty_cat/_super_vectorizer.py
  dirty_cat/_utils.py
  dirty_cat/tests/test_gap_encoder.py
  dirty_cat/tests/test_similarity_encoder.py
  dirty_cat/tests/test_super_vectorizer.py
  dirty_cat/tests/test_utils.py
Labels: enhancement

#413 Fix random fetching error
  dirty_cat/datasets/_fetching.py
  dirty_cat/datasets/tests/test_fetching.py
Labels: bug
