Repository skrub-data/skrub, pull requests merged in 2022-10, with the labels that each got.

#386 Remove example 5
  CHANGES.rst
  examples/05_dimension_reduction_and_performance.py
  examples/05_scaling_non_linear_models.py
  examples/06_joining_tables_with_FuzzyJoin.py
Labels: Documentation

#359 Fix fetching functions doc generation
  dirty_cat/datasets/__init__.py
  dirty_cat/datasets/_fetching.py
  dirty_cat/datasets/tests/test_fetching.py
  doc/index.rst
  doc/unlisted.rst
Labels: bug, Documentation

#394 Fix generated doc push to website
  .circleci/config.yml
  build_tools/circle/build_doc.sh
  build_tools/circle/push_doc.sh
Labels: bug, CI / Build

#388 Add warning banner on development documentation
  doc/_static/custom.css
  doc/_templates/about.html
  doc/conf.py
Labels: Documentation, CI / Build

#395 Standardize doc of examples
  dirty_cat/_fuzzy_join.py
  examples/01_dirty_categories.py
  examples/02_investigating_dirty_categories.py
  examples/03_datetime_encoder.py
  examples/04_dimension_reduction_and_performance.py
  examples/05_joining_tables_with_FuzzyJoin.py
Labels: Documentation
