Repository skrub-data/skrub, pull requests merged in 2022-12, with the labels that each got.

#433 Replace np.array with np.ndarray in type hints
  dirty_cat/_datetime_encoder.py
  dirty_cat/_gap_encoder.py
  dirty_cat/_similarity_encoder.py
  dirty_cat/_target_encoder.py
  dirty_cat/_utils.py
  dirty_cat/tests/test_super_vectorizer.py
Labels: Documentation, No Changelog Needed

#430 Small improvement to fetching path logic
  dirty_cat/datasets/_fetching.py
Labels: No Changelog Needed

#438 DOC Ensures that `GapEncoder` passes numpydoc validation
  dirty_cat/_gap_encoder.py
  dirty_cat/tests/test_docstrings.py
Labels: Documentation, No Changelog Needed

#444 ENH Improve coverage of SimilarityEncoder
  dirty_cat/_similarity_encoder.py
  dirty_cat/tests/test_similarity_encoder.py
Labels: CI / Build, No Changelog Needed

#435 Fix em dash in website titles
  doc/conf.py
Labels: Documentation, No Changelog Needed
