Repository skrub-data/skrub, pull requests merged in 2023-06, with the labels that each got.

#570 Use modern issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/doc_improvement.yml
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: Documentation, No Changelog Needed

#514 Clean signatures for cleaner calls
  CHANGES.rst
  skrub/_datetime_encoder.py
  skrub/_deduplicate.py
  skrub/_feature_augmenter.py
  skrub/_gap_encoder.py
  skrub/_minhash_encoder.py
  skrub/_similarity_encoder.py
  skrub/_target_encoder.py
  skrub/datasets/_fetching.py
  skrub/tests/test_minhash_encoder.py
Labels: enhancement

#569 Improve README
  README.rst
Labels: Documentation, No Changelog Needed

#582 Parallelize the `GapEncoder`
  CHANGES.rst
  skrub/_gap_encoder.py
Labels: enhancement

#579 TableVectorize cleanup!
  CHANGES.rst
  skrub/_table_vectorizer.py
  skrub/tests/test_table_vectorizer.py
Labels: enhancement

#571 Website improvements
  .github/workflows/changelog.yml
  CONTRIBUTING.rst
  LICENSE.txt
  doc/_static/scrolltoc.js
  doc/_static/stable_doc_redirect.js
  doc/_templates/index.html
  doc/announcement.html
  doc/api.rst
  doc/conf.py
  doc/index.rst
  doc/install.rst
  setup.cfg
Labels: Documentation, No Changelog Needed

#612 Normalize tags
  .github/ISSUE_TEMPLATE/doc_improvement.yml
  .github/workflows/changelog.yml
Labels: No Changelog Needed

#613 Bump requirements
  CHANGES.rst
  examples/01_dirty_categories.py
  examples/04_fuzzy_joining_and_FeatureAugmenter.py
  setup.cfg
  skrub/_datetime_encoder.py
  skrub/_gap_encoder.py
  skrub/_similarity_encoder.py
  skrub/_table_vectorizer.py
  skrub/_utils.py
  skrub/tests/test_gap_encoder.py
  skrub/tests/test_similarity_encoder.py
  skrub/tests/test_table_vectorizer.py
Labels: dependencies

#614 DOC: add a large 'coming soon' note
  doc/_static/css/custom.css
  doc/_templates/index.html
  doc/announcement.html
Labels: no changelog needed

#609 Use modern type hinting
  CHANGES.rst
  benchmarks/bench_fuzzy_join_sparse_vs_dense.py
  benchmarks/bench_minhash_batch_number.py
  benchmarks/bench_tablevectorizer_tuning.py
  benchmarks/utils/_various.py
  benchmarks/utils/join.py
  benchmarks/utils/monitor.py
  setup.cfg
  skrub/_datetime_encoder.py
  skrub/_deduplicate.py
  skrub/_fast_hash.py
  skrub/_feature_augmenter.py
  skrub/_fuzzy_join.py
  skrub/_gap_encoder.py
  skrub/_minhash_encoder.py
  skrub/_similarity_encoder.py
  skrub/_string_distances.py
  skrub/_table_vectorizer.py
  skrub/_target_encoder.py
  skrub/_utils.py
  skrub/datasets/_fetching.py
  skrub/datasets/_generating.py
  skrub/datasets/_ken_embeddings.py
  skrub/datasets/_utils.py
  skrub/tests/test_deduplicate.py
  skrub/tests/test_docstrings.py
  skrub/tests/test_similarity_encoder.py
  skrub/tests/test_string_distances.py
  skrub/tests/test_table_vectorizer.py
  skrub/tests/utils.py
Labels: enhancement

#619 FEA Add analyzer parameter to SimilarityEncoder
  CHANGES.rst
  skrub/_similarity_encoder.py
  skrub/tests/test_similarity_encoder.py
Labels: enhancement
