Repository skrub-data/skrub, pull requests merged in 2023-08, with the labels that each got.

#683 Rework `DatetimeEncoder` example
  examples/03_datetime_encoder.py
Labels: documentation, no changelog needed

#665 Create a script to run the TableVectorizer on all openml datasets
  benchmarks/run_on_openml_datasets.py
  setup.cfg
Labels: benchmarks

#581 Merge `underfilled_job_title` with `employee_position_title` in `employee_salaries`
  CHANGES.rst
  skrub/datasets/_fetching.py
Labels: enhancement

#583 Add built-in column-specific transformers to `TableVectorizer`
  CHANGES.rst
  examples/FIXME/07_grid_searching_with_the_tablevectorizer.py
  skrub/_table_vectorizer.py
  skrub/tests/test_table_vectorizer.py
Labels: enhancement
