Repository skrub-data/skrub, pull requests merged in 2023-01, with the labels that each got.

#431 Various minor style improvements
  CHANGES.rst
  CONTRIBUTING.rst
  examples/01_dirty_categories.py
  examples/02_investigating_dirty_categories.py
  examples/04_dimension_reduction_and_performance.py
  examples/05_joining_tables_with_FuzzyJoin.py
Labels: Documentation, No Changelog Needed

#439 Improve docstrings and add function support to test
  dirty_cat/_datetime_encoder.py
  dirty_cat/_fuzzy_join.py
  dirty_cat/_gap_encoder.py
  dirty_cat/_minhash_encoder.py
  dirty_cat/_similarity_encoder.py
  dirty_cat/_super_vectorizer.py
  dirty_cat/_target_encoder.py
  dirty_cat/tests/test_docstrings.py
Labels: Documentation, CI / Build, No Changelog Needed

#420 Added HashingVectorizer to fuzzy_join.
  dirty_cat/_fuzzy_join.py
  dirty_cat/tests/test_fuzzy_join.py
  dirty_cat/tests/utils.py
Labels: No Changelog Needed

#409 FEA Adding FeatureAugmenter
  CHANGES.rst
  dirty_cat/__init__.py
  dirty_cat/_feature_augmenter.py
  dirty_cat/_fuzzy_join.py
  dirty_cat/tests/test_feature_augmenter.py
  doc/index.rst
  examples/05_fuzzy_joining_with_FeatureAugmenter.py
Labels: enhancement

#468 DOC: fuzzy join example
  examples/05_fuzzy_joining_and_FeatureAugmenter.py
Labels: Documentation, No Changelog Needed

#465 ENH: more didactic deduplicate example
  dirty_cat/datasets/__init__.py
  dirty_cat/datasets/_fetching.py
  dirty_cat/datasets/_generating.py
  dirty_cat/datasets/tests/test_fetching.py
  dirty_cat/datasets/tests/test_generating.py
  doc/index.rst
  examples/05_fuzzy_joining_and_FeatureAugmenter.py
  examples/06_deduplication.py
Labels: No Changelog Needed

#463 Use `check_is_fitted` for all dirty_cat transformers.
  dirty_cat/_gap_encoder.py
  dirty_cat/_minhash_encoder.py
  dirty_cat/_similarity_encoder.py
  dirty_cat/_super_vectorizer.py
  dirty_cat/tests/test_datetime_encoder.py
  dirty_cat/tests/test_gap_encoder.py
  dirty_cat/tests/test_minhash_encoder.py
  dirty_cat/tests/test_similarity_encoder.py
  dirty_cat/tests/test_super_vectorizer.py
  dirty_cat/tests/test_target_encoder.py
Labels: No Changelog Needed

#464 Run pre-commit hooks on all files
  .github/ISSUE_TEMPLATE/documentation.md
  .gitignore
  .pre-commit-config.yaml
  CODE_OF_CONDUCT.md
  benchmarks/bench_minhash.py
  benchmarks/get_results.py
  benchmarks/similarity_scores_time_benchmark.py
  benchmarks/supervectorizer_tuning.py
  dirty_cat/_gap_encoder.py
  dirty_cat/_similarity_encoder.py
  dirty_cat/tests/test_minhash_encoder.py
  examples/README.txt
Labels: No Changelog Needed

#475 More informative error when n_samples < n_components in GapEncoder
  dirty_cat/_gap_encoder.py
  dirty_cat/tests/test_gap_encoder.py
Labels: No Changelog Needed

#478 DOC Add website sections for new features
  doc/_static/custom.css
  doc/index.rst
  examples/01_dirty_categories.py
  examples/02_investigating_dirty_categories.py
  examples/05_fuzzy_joining_and_FeatureAugmenter.py
  examples/06_deduplication.py
Labels: No Changelog Needed
