Repository skrub-data/skrub, pull requests merged in 2023-05, with the labels that each got.

#553 Fix CircleCI artifacts not rendering
  .github/workflows/main.yml
Labels: bug, CI / Build, No Changelog Needed

#551 Maintenance before migration
  benchmarks/bench_minhash_batch.py
  dirty_cat/_datetime_encoder.py
  dirty_cat/_deduplicate.py
  dirty_cat/_fast_hash.py
  dirty_cat/_feature_augmenter.py
  dirty_cat/_fuzzy_join.py
  dirty_cat/_gap_encoder.py
  dirty_cat/_minhash_encoder.py
  dirty_cat/_similarity_encoder.py
  dirty_cat/_string_distances.py
  dirty_cat/_table_vectorizer.py
  dirty_cat/_target_encoder.py
  dirty_cat/datasets/_fetching.py
  dirty_cat/datasets/_generating.py
  dirty_cat/datasets/_ken_embeddings.py
  dirty_cat/datasets/_utils.py
  dirty_cat/datasets/tests/test_generating.py
  dirty_cat/tests/test_datetime_encoder.py
  dirty_cat/tests/test_deduplicate.py
  dirty_cat/tests/test_docstrings.py
  dirty_cat/tests/test_fast_hash.py
  dirty_cat/tests/test_feature_augmenter.py
  dirty_cat/tests/test_fuzzy_join.py
  dirty_cat/tests/test_gap_encoder.py
  dirty_cat/tests/test_minhash_encoder.py
  dirty_cat/tests/test_similarity_encoder.py
  dirty_cat/tests/test_sklearn.py
  dirty_cat/tests/test_table_vectorizer.py
  dirty_cat/tests/test_target_encoder.py
  doc/index.rst
  doc/unlisted.rst
Labels: enhancement, Documentation, No Changelog Needed

#565 Working on the website
  doc/announcement.html
  doc/api.rst
  doc/conf.py
  doc/documentation.rst
  doc/index.rst
  examples/README.txt
Labels: No Changelog Needed
