Repository skrub-data/skrub, pull requests merged in 2023-03, with the labels that each got.

#516 Fix CI not running tests
  .github/workflows/testing.yml
Labels: bug, CI / Build, No Changelog Needed

#526 Fix duplicate CI workers
  .github/workflows/testing.yml
Labels: bug, CI / Build, No Changelog Needed

#524 Shorten fetching tests
  build_tools/github/install.sh
  dirty_cat/datasets/tests/test_fetching.py
  setup.cfg
Labels: enhancement, CI / Build, No Changelog Needed

#534 FIX Error when wrong type of fuzzy_join parameter
  dirty_cat/_fuzzy_join.py
  dirty_cat/_similarity_encoder.py
  dirty_cat/tests/test_fuzzy_join.py
Labels: No Changelog Needed
