Repository skrub-data/skrub, pull requests merged in 2023-07, with the labels that each got.

#620 Use modern numpy type hints
  skrub/_datetime_encoder.py
  skrub/_deduplicate.py
  skrub/_fast_hash.py
  skrub/_fuzzy_join.py
  skrub/_gap_encoder.py
  skrub/_minhash_encoder.py
  skrub/_similarity_encoder.py
  skrub/_string_distances.py
  skrub/_table_vectorizer.py
  skrub/_target_encoder.py
  skrub/_utils.py
  skrub/tests/utils.py
Labels: documentation, no changelog needed

#645 CI Turn deprecation warnings into errors
  pyproject.toml
  setup.cfg
  skrub/_gap_encoder.py
  skrub/_table_vectorizer.py
  skrub/tests/test_deduplicate.py
Labels: no changelog needed

#650 added duplicate column names features
  skrub/_table_vectorizer.py
  skrub/tests/test_table_vectorizer.py
Labels: no changelog needed

#656 Populate xref
  benchmarks/bench_fuzzy_join_sparse_vs_dense.py
  doc/conf.py
  skrub/_datetime_encoder.py
  skrub/_deduplicate.py
  skrub/_feature_augmenter.py
  skrub/_fuzzy_join.py
  skrub/_gap_encoder.py
  skrub/_minhash_encoder.py
  skrub/_similarity_encoder.py
  skrub/_table_vectorizer.py
  skrub/_target_encoder.py
  skrub/datasets/_fetching.py
  skrub/datasets/_generating.py
  skrub/datasets/_ken_embeddings.py
Labels: enhancement, documentation, no changelog needed

#659 Add blank issue template
  .github/ISSUE_TEMPLATE/config.yml
Labels: no changelog needed

#661 Fix blank issue template URL
  .github/ISSUE_TEMPLATE/config.yml
Labels: bug, no changelog needed

#664 MAINT Fix CI linter check and fix linting issues
  .github/workflows/changelog.yml
  .github/workflows/run-code-format-checks.yaml
  benchmarks/bench_fuzzy_join_sparse_vs_dense.py
  benchmarks/bench_fuzzy_join_vs_others.py
  benchmarks/bench_minhash_batch_number.py
  benchmarks/bench_tablevectorizer_tuning.py
  benchmarks/utils/__init__.py
  benchmarks/utils/_various.py
  benchmarks/utils/join.py
  benchmarks/utils/monitor.py
  doc/conf.py
  doc/sphinxext/github_link.py
  doc/sphinxext/sphinx_issues.py
  examples/01_dirty_categories.py
  examples/02_investigating_dirty_categories.py
  examples/03_datetime_encoder.py
  examples/04_fuzzy_joining_and_FeatureAugmenter.py
  examples/05_deduplication.py
  examples/06_ken_embeddings_example.py
  setup.cfg
  setup.py
  skrub/_check_dependencies.py
  skrub/_datetime_encoder.py
  skrub/_gap_encoder.py
  skrub/_target_encoder.py
  skrub/datasets/__init__.py
  skrub/datasets/_fetching.py
  skrub/datasets/tests/test_ken_embeddings.py
  skrub/tests/test_fuzzy_join.py
  skrub/tests/test_similarity_encoder.py
  skrub/tests/test_sklearn.py
  skrub/tests/test_table_vectorizer.py
Labels: CI / build, no changelog needed

#672 Fix randomly failing deduplicate test
  skrub/tests/test_deduplicate.py
Labels: no changelog needed

#666 Use errors='coerce' when converting to numerical or datetime in `TableVectorizer`'s `_apply_cast`
  CHANGES.rst
  skrub/_table_vectorizer.py
  skrub/_utils.py
  skrub/tests/test_table_vectorizer.py
Labels: no changelog needed

#676 FIX Broken links after dataset folder moved
  examples/04_fuzzy_joining_and_FeatureAugmenter.py
  skrub/datasets/_ken_embeddings.py
  skrub/datasets/tests/test_fetching.py
Labels: no changelog needed
