Repository skrub-data/skrub, pull requests merged in 2023-11, with the labels that each got.

#787 Add JupyterCon talk link
  README.rst
Labels: documentation

#686 DOC Rework `GapEncoder` example
  examples/02_feature_interpretation_with_gapencoder.py
  examples/02_investigating_dirty_categories.py
Labels: documentation, no changelog needed

#829 [FEAT] Drop the TargetEncoder entirely
  CHANGES.rst
  doc/api.rst
  examples/08_join_aggregation.py
  skrub/__init__.py
  skrub/_target_encoder.py
  skrub/tests/test_sklearn.py
  skrub/tests/test_target_encoder.py
Labels: no changelog needed

#841 [MRG] FIX: GapEncoder get_feature_names_out on short words
  skrub/_gap_encoder.py
  skrub/tests/test_gap_encoder.py
Labels: no changelog needed
