Repository skrub-data/skrub, pull requests merged in 2023-02, with the labels that each got.

#491 Fix CI issue
  build_tools/circle/build_doc.sh
Labels: CI / Build

#492 Set default value to None for similarity in SimilarityEncoder
  dirty_cat/_similarity_encoder.py
Labels: bug

#489 Refactor fetching tests
  dirty_cat/datasets/_fetching.py
  dirty_cat/datasets/tests/test_fetching.py
Labels: CI / Build, No Changelog Needed

#493 Parallelize parametrized tests
  build_tools/github/test.sh
  dirty_cat/tests/test_minhash_encoder.py
  setup.cfg
Labels: CI / Build, No Changelog Needed

#453 Support paths as strings in public fetching API
  CHANGES.rst
  dirty_cat/datasets/_fetching.py
  dirty_cat/datasets/tests/test_fetching.py
Labels: enhancement

#494 Fix long CI install
  build_tools/github/install.sh
  setup.cfg
Labels: bug, CI / Build, No Changelog Needed

#502 Ci improvements
  .circleci/config.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/main.yml
  .github/workflows/testing.yml
Labels: CI / Build, No Changelog Needed

#501 Support paths as strings in public fetching API
  CHANGES.rst
  dirty_cat/datasets/_fetching.py
  dirty_cat/datasets/tests/test_fetching.py
Labels: No Changelog Needed

#509 FIX fuzzy_join AttributeError
  dirty_cat/_fuzzy_join.py
  dirty_cat/tests/test_fuzzy_join.py
Labels: No Changelog Needed

#434 ENH Improve coverage of GapEncoder
  dirty_cat/_gap_encoder.py
  dirty_cat/tests/test_gap_encoder.py
Labels: CI / Build, No Changelog Needed

#504 DOC Ensures that `SimilarityEncoder` passes numpydoc validation
  dirty_cat/_similarity_encoder.py
Labels: Documentation, No Changelog Needed
