Repository skrub-data/skrub, pull requests merged in 2025-06, with the labels that each got.

#1445 Provide informative errors when expressions are passed as values to skrub variables
  skrub/_expressions/_expressions.py
  skrub/_expressions/tests/test_expressions.py
Labels: no changelog needed, expressions

#1460 Improve doc api reference
  .gitignore
  CONTRIBUTING.rst
  doc/api_reference.py
  doc/conf.py
  doc/documentation.rst
  doc/reference/index.rst
  doc/reference/index.rst.template
  doc/reference/module.rst.template
  doc/sphinxext/autoshortsummary.py
  skrub/selectors/__init__.py
Labels: documentation

#1467 correct missing line and point (.)
  skrub/_expressions/_skrub_namespace.py
Labels: documentation

#1450 Expand section on datetime encoding in user guide
  doc/encoding.rst
Labels: no changelog needed

#1458 Shortening docstring preamble and moving text to the notes
  skrub/_column_associations.py
  skrub/_drop_uninformative.py
  skrub/_expressions/_expressions.py
  skrub/_expressions/_skrub_namespace.py
  skrub/_table_vectorizer.py
  skrub/_text_encoder.py
  skrub/_to_categorical.py
  skrub/_to_datetime.py
Labels: no changelog needed
