Repository skrub-data/skrub, pull requests merged in 2025-07, with the labels that each got.

#1515 Fixing and slightly extending docstring
  CONTRIBUTING.rst
Labels: documentation, no changelog needed

#1522 DOC: reworking DataOps intro example
  doc/_templates/index.html
  doc/api_reference.py
  doc/data_ops_report.py
  doc/skrub_pipeline.rst
  doc/userguide_selectors.rst
  examples/00_getting_started.py
  examples/10_apply_on_cols.py
  examples/data_ops/10_data_ops_intro.py
  examples/data_ops/10_expressions_intro.py
  examples/data_ops/11_multiple_tables.py
  examples/data_ops/12_choices.py
  examples/data_ops/13_subsampling.py
  skrub/_reporting/_table_report.py
  skrub/_select_cols.py
  skrub/tests/test_expression_stack_description.py
Labels: documentation, no changelog needed, data_ops

#1521 Preparing an extended version of the changelog for the upcoming release
  CHANGES.rst
Labels: no changelog needed

#1534 FIX Renaming more instances of "expression" to "data_op" in the codebase
  .github/workflows/check_stub_files_diff.yaml
  build_tools/generate_data_ops_stub.py
  doc/_templates/index.html
  doc/conf.py
  doc/generate_data_ops_example_for_index.py
  skrub/_config.py
  skrub/_data_ops/_estimator.py
  skrub/_data_ops/_inspection.py
  skrub/_data_ops/_skrub_namespace.py
  skrub/_data_ops/tests/test_interactive_features.py
  skrub/_reporting/_data/templates/data_ops/node.html
  skrub/tests/test_config.py
  skrub/tests/test_data_ops_stack_description.py
Labels: no changelog needed

#1488 Dont use preview in eval
  skrub/_data_ops/_data_ops.py
  skrub/_data_ops/_skrub_namespace.py
  skrub/_data_ops/tests/test_data_ops.py
  skrub/_data_ops/tests/test_expressions.py
Labels: no changelog needed, data_ops

#1544 DOC - Small fixes to changelog, user guide, and examples
  CHANGES.rst
  doc/api_reference.py
  doc/userguide_data_ops_ml_pipeline.rst
  doc/userguide_datetimes.rst
  doc/userguide_encoders.rst
  doc/userguide_tablereport.rst
  doc/userguide_utils.rst
  examples/07_multiple_key_join.py
  examples/data_ops/10_data_ops_intro.py
  skrub/_data_ops/_skrub_namespace.py
  skrub/_table_vectorizer.py
Labels: no changelog needed
