Repository skrub-data/skrub, pull requests merged in 2025-09, with the labels that each got.

#1610 avoid extra predict in dataops fit
  CHANGES.rst
  doc/userguide_data_ops_validation.rst
  examples/data_ops/11_data_ops_intro.py
  examples/data_ops/12_multiple_tables.py
  examples/data_ops/13_choices.py
  examples/data_ops/14_subsampling.py
  examples/data_ops/15_use_case.py
  skrub/_data_ops/_data_ops.py
  skrub/_data_ops/_estimator.py
  skrub/_data_ops/_evaluation.py
  skrub/_data_ops/_skrub_namespace.py
  skrub/_data_ops/tests/test_data_ops.py
Labels: data_ops

#1623 show transformed data not dataop itself in fit report
  CHANGES.rst
  skrub/_data_ops/_evaluation.py
  skrub/_data_ops/tests/test_evaluation.py
  skrub/_data_ops/tests/test_inspection.py
Labels: bug, data_ops

#1578 DOC - adding a guide on how to write examples
  CONTRIBUTING.rst
  doc/development.rst
  doc/tutorial_example.rst
Labels: documentation

#1631 FIX - doctest failing
  skrub/_data_ops/_skrub_namespace.py
Labels: no changelog needed

#1634 MAINT refactoring get_feature_names_out to define it in encoders
  skrub/_apply_to_cols.py
  skrub/_datetime_encoder.py
  skrub/_minhash_encoder.py
  skrub/_string_encoder.py
  skrub/_text_encoder.py
  skrub/tests/test_datetime_encoder.py
Labels: no changelog needed
